#!/bin/bash
# ============================================================================
# HeliosProxy Configuration Generator
# ============================================================================
#
# Generates a proxy.toml from environment variables. Useful for container
# orchestration (Docker, Kubernetes) where config is injected via env vars.
#
# Usage:
#   ./gen-config.sh                         # Print to stdout
#   ./gen-config.sh > /etc/helios/proxy.toml  # Write to file
#   ./gen-config.sh -o /etc/helios/proxy.toml # Write to file (flag)
#
# Required environment variables:
#   PROXY_PRIMARY      Primary node address (host:port)
#
# Optional environment variables:
#   PROXY_LISTEN       Listen address          (default: 0.0.0.0:6432)
#   PROXY_ADMIN        Admin API address       (default: 0.0.0.0:9090)
#   PROXY_STANDBYS     Comma-separated standby addresses (host:port,host:port)
#   PROXY_REPLICAS     Comma-separated read replica addresses
#   PROXY_POOL_MODE    Pool mode: session|transaction|statement (default: transaction)
#   PROXY_POOL_MIN     Min connections per node (default: 2)
#   PROXY_POOL_MAX     Max connections per node (default: 100)
#   PROXY_IDLE_TIMEOUT Pool idle timeout secs   (default: 300)
#   PROXY_TR_ENABLED   Enable Transaction Replay (default: true)
#   PROXY_TR_MODE      TR mode: none|session|select|transaction (default: session)
#   PROXY_LB_STRATEGY  Load balancer strategy   (default: round_robin)
#   PROXY_RW_SPLIT     Enable read/write split  (default: true)
#   PROXY_HC_INTERVAL  Health check interval sec (default: 5)
#   PROXY_HC_TIMEOUT   Health check timeout sec  (default: 3)
#   PROXY_HC_FAILURES  Failure threshold         (default: 3)
#   PROXY_HC_SUCCESSES Success threshold          (default: 2)
#   PROXY_WRITE_TIMEOUT Write timeout during failover sec (default: 30)
#
# ============================================================================

set -euo pipefail

# ── Defaults ─────────────────────────────────────────────────────────
LISTEN="${PROXY_LISTEN:-0.0.0.0:6432}"
ADMIN="${PROXY_ADMIN:-0.0.0.0:9090}"
PRIMARY="${PROXY_PRIMARY:-}"
STANDBYS="${PROXY_STANDBYS:-}"
REPLICAS="${PROXY_REPLICAS:-}"
POOL_MODE="${PROXY_POOL_MODE:-transaction}"
POOL_MIN="${PROXY_POOL_MIN:-2}"
POOL_MAX="${PROXY_POOL_MAX:-100}"
IDLE_TIMEOUT="${PROXY_IDLE_TIMEOUT:-300}"
TR_ENABLED="${PROXY_TR_ENABLED:-true}"
TR_MODE="${PROXY_TR_MODE:-session}"
LB_STRATEGY="${PROXY_LB_STRATEGY:-round_robin}"
RW_SPLIT="${PROXY_RW_SPLIT:-true}"
HC_INTERVAL="${PROXY_HC_INTERVAL:-5}"
HC_TIMEOUT="${PROXY_HC_TIMEOUT:-3}"
HC_FAILURES="${PROXY_HC_FAILURES:-3}"
HC_SUCCESSES="${PROXY_HC_SUCCESSES:-2}"
WRITE_TIMEOUT="${PROXY_WRITE_TIMEOUT:-30}"
OUTPUT=""

# ── Parse arguments ──────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        -o|--output)
            OUTPUT="$2"
            shift 2
            ;;
        -h|--help)
            head -n 35 "$0" | tail -n +2 | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# ── Validate ─────────────────────────────────────────────────────────
if [ -z "$PRIMARY" ]; then
    echo "Error: PROXY_PRIMARY is required (e.g., PROXY_PRIMARY=pg-primary:5432)" >&2
    exit 1
fi

# ── Generate TOML ───────────────────────────────────────────────────
generate() {
cat << TOML
# HeliosProxy Configuration
# Generated by gen-config.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

listen_address = "${LISTEN}"
admin_address  = "${ADMIN}"

tr_enabled = ${TR_ENABLED}
tr_mode    = "${TR_MODE}"

write_timeout_secs = ${WRITE_TIMEOUT}

# ── Connection Pool ──────────────────────────────────────────────────
[pool]
min_connections      = ${POOL_MIN}
max_connections      = ${POOL_MAX}
idle_timeout_secs    = ${IDLE_TIMEOUT}
max_lifetime_secs    = 1800
acquire_timeout_secs = 10
test_on_acquire      = true

# ── Pool Mode ────────────────────────────────────────────────────────
[pool_mode]
mode                    = "${POOL_MODE}"
max_pool_size           = ${POOL_MAX}
min_idle                = ${POOL_MIN}
idle_timeout_secs       = 600
max_lifetime_secs       = 3600
acquire_timeout_secs    = 5
reset_query             = "DISCARD ALL"
prepared_statement_mode = "track"

# ── Load Balancer ────────────────────────────────────────────────────
[load_balancer]
read_strategy        = "${LB_STRATEGY}"
read_write_split     = ${RW_SPLIT}
latency_threshold_ms = 100

# ── Health Checks ────────────────────────────────────────────────────
[health]
check_interval_secs = ${HC_INTERVAL}
check_timeout_secs  = ${HC_TIMEOUT}
failure_threshold   = ${HC_FAILURES}
success_threshold   = ${HC_SUCCESSES}
check_query         = "SELECT 1"

# ── Backend Nodes ────────────────────────────────────────────────────
TOML

    # Primary node
    local primary_host="${PRIMARY%%:*}"
    local primary_port="${PRIMARY##*:}"
    cat << TOML

[[nodes]]
host    = "${primary_host}"
port    = ${primary_port}
role    = "primary"
weight  = 100
enabled = true
name    = "primary"
TOML

    # Standby nodes
    if [ -n "$STANDBYS" ]; then
        local i=1
        IFS=',' read -ra STANDBY_LIST <<< "$STANDBYS"
        for addr in "${STANDBY_LIST[@]}"; do
            addr=$(echo "$addr" | xargs)  # trim whitespace
            local s_host="${addr%%:*}"
            local s_port="${addr##*:}"
            cat << TOML

[[nodes]]
host    = "${s_host}"
port    = ${s_port}
role    = "standby"
weight  = 100
enabled = true
name    = "standby-${i}"
TOML
            i=$((i + 1))
        done
    fi

    # Read replica nodes
    if [ -n "$REPLICAS" ]; then
        local j=1
        IFS=',' read -ra REPLICA_LIST <<< "$REPLICAS"
        for addr in "${REPLICA_LIST[@]}"; do
            addr=$(echo "$addr" | xargs)
            local r_host="${addr%%:*}"
            local r_port="${addr##*:}"
            cat << TOML

[[nodes]]
host    = "${r_host}"
port    = ${r_port}
role    = "replica"
weight  = 100
enabled = true
name    = "replica-${j}"
TOML
            j=$((j + 1))
        done
    fi
}

# ── Output ───────────────────────────────────────────────────────────
if [ -n "$OUTPUT" ]; then
    mkdir -p "$(dirname "$OUTPUT")"
    generate > "$OUTPUT"
    echo "Configuration written to ${OUTPUT}" >&2
else
    generate
fi
